[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
command = "tuigreet --cmd Hyprland --greeting 'cans pc! you need to login' --asterisks --asterisks-char 'C' --power-shutdown 'sudo systemctl poweroff' --power-reboot 'sudo systemctl reboot'  --theme 'border=magenta;text=cyan;prompt=blue;time=magenta;action=magenta;button=cyan;container=black;input=cyan'"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
# run the following command: sudo useradd -m -G video -s /usr/bin/nologin greeter
user = "greeter"

