[font]
size = 13.0

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[colors.primary]
background = "#011a1c"
foreground = "#baf4ff"

[colors.normal]
black = "#011a1c"
red = "#fc514e"
green = "#a1cd5e"
yellow = "#e3d18a"
blue = "#82aaff"
magenta = "#ae81ff"
cyan = "#296596"
white = "#c8dde6"

