#!/usr/bin/env bash

    if [[ "$1" == 'shutdown' ]]; then
        systemctl poweroff
    elif [[ "$1" == 'reboot' ]]; then
        systemctl reboot
    elif [[ "$1" == 'hibernate' ]]; then
        playerctl --all-players stop
        ~/.scripts/lock
        sleep 0.5s
        systemctl suspend-then-hibernate
    elif [[ "$1" == 'lock' ]]; then
        ~/.scripts/lock
    elif [[ "$1" == 'suspend' ]]; then
        playerctl --all-players stop
        ~/.scripts/lock
        sleep 0.5s
        systemctl suspend
    elif [[ "$1" == 'logout' ]]; then
        hyprctl dispatch exit none
    fi
